# Generated by Django 5.1.2 on 2024-10-23 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('path', models.CharField(max_length=65536, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'episodes',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=65536)),
            ],
            options={
                'verbose_name_plural': 'shows',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_text', models.CharField(max_length=65536)),
                ('quote_start', models.TimeField()),
                ('quote_end', models.TimeField()),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.episode')),
            ],
            options={
                'verbose_name_plural': 'quotes',
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show'),
        ),
    ]
