# Generated by Django 4.2.12 on 2024-10-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(default='41b2debb0cde4070a7e9a0eac768e78f', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'keys',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('path', models.CharField(max_length=65536, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'episodes',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=65536)),
            ],
            options={
                'verbose_name_plural': 'shows',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_index', models.IntegerField()),
                ('quote_text', models.CharField(max_length=65536)),
                ('quote_start', models.TimeField()),
                ('quote_end', models.TimeField()),
                ('quote_thumb_path', models.CharField(max_length=65563)),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.episode')),
            ],
            options={
                'verbose_name_plural': 'quotes',
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show'),
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('clip_id', models.AutoField(primary_key=True, serialize=False)),
                ('clip_path', models.CharField(max_length=65536)),
                ('clip_start', models.TimeField()),
                ('clip_end', models.TimeField()),
                ('clip_creation', models.TimeField(auto_now=True)),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.quote')),
            ],
            options={
                'verbose_name_plural': 'clips',
            },
        ),
    ]
