# Generated by Django 5.1.2 on 2024-10-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
