# Generated by Django 5.1.2 on 2024-10-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_quote_quote_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('clip_id', models.AutoField(primary_key=True, serialize=False)),
                ('clip_path', models.CharField(max_length=65536)),
                ('clip_start', models.TimeField()),
                ('clip_end', models.TimeField()),
                ('clip_creation', models.TimeField(auto_now=True)),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.quote')),
            ],
            options={
                'verbose_name_plural': 'clips',
            },
        ),
    ]
