# Generated by Django 5.1.2 on 2024-10-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_thumb_path',
            field=models.CharField(default=1, max_length=65563),
            preserve_default=False,
        ),
    ]
