# Generated by Django 5.1.2 on 2024-10-26 02:32

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_quote_quote_thumb_path'),
    ]

    operations = [
            TrigramExtension(),
    ]
